# The exact plugin name, you can see this by running /plugins in your console.
hide-plugins:
  -
show-version: true
# LIST - Show plugins on one line
# LINE - Show plugins on a list
# Defaults to LINE
style: LINE
# Prefix the text sent. You can use any hex color code.
text-style:
  title:
    plugin-title: "&6"
    plugin-version: "&a"
  hover:
    plugin-title: "&6&b"
    plugin-api-version: "&a"
    plugin-description: "&7"
    plugin-link: "&5&b"